# Generated by Django 4.2 on 2025-08-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='usename',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
