# Generated by Django 4.2 on 2025-08-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_register_password_register_usename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
        migrations.RemoveField(
            model_name='register',
            name='usename',
        ),
    ]
