# Generated by Django 4.2 on 2025-08-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menucard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
