# Generated by Django 4.2 on 2025-08-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_menucard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_date', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('total_participants', models.CharField(max_length=50)),
                ('event_venue', models.CharField(max_length=50)),
                ('event_location', models.CharField(max_length=100)),
                ('event_ticket_price', models.CharField(max_length=50)),
                ('event_guest', models.CharField(max_length=50)),
                ('event_poster', models.ImageField(blank=True, null=True, upload_to='event_posters/')),
            ],
        ),
    ]
